/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

import {
  CircuitZKit,
  CircuitZKitConfig,
  Groth16Proof,
  PlonkProof,
  Groth16ProofPoints,
  PlonkProofPoints,
  NumberLike,
  NumericString,
  PublicSignals,
  Groth16Implementer,
  PlonkImplementer,
} from "@solarity/zkit";

import { normalizePublicSignals, denormalizePublicSignals } from "../helpers";

export type PrivateBurnCircuitGroth16 = {
  ValueToBurn: NumberLike;
  SenderPrivateKey: NumberLike;
  SenderPublicKey: NumberLike[];
  SenderBalance: NumberLike;
  SenderBalanceC1: NumberLike[];
  SenderBalanceC2: NumberLike[];
  SenderVTBC1: NumberLike[];
  SenderVTBC2: NumberLike[];
  AuditorPublicKey: NumberLike[];
  AuditorPCT: NumberLike[];
  AuditorPCTAuthKey: NumberLike[];
  AuditorPCTNonce: NumberLike;
  AuditorPCTRandom: NumberLike;
};

export type PublicBurnCircuitGroth16 = {
  SenderPublicKey: NumberLike[];
  SenderBalanceC1: NumberLike[];
  SenderBalanceC2: NumberLike[];
  SenderVTBC1: NumberLike[];
  SenderVTBC2: NumberLike[];
  AuditorPublicKey: NumberLike[];
  AuditorPCT: NumberLike[];
  AuditorPCTAuthKey: NumberLike[];
  AuditorPCTNonce: NumberLike;
};

export type ProofBurnCircuitGroth16 = {
  proof: Groth16Proof;
  publicSignals: PublicBurnCircuitGroth16;
};

export type CalldataBurnCircuitGroth16 = {
  proofPoints: Groth16ProofPoints;
  publicSignals: [
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
  ];
};

export class BurnCircuit extends CircuitZKit<"groth16"> {
  constructor(config: CircuitZKitConfig) {
    super(config, new Groth16Implementer());
  }

  public async generateProof(
    inputs: PrivateBurnCircuitGroth16,
  ): Promise<ProofBurnCircuitGroth16> {
    const proof = await super.generateProof(inputs as any);

    return {
      proof: proof.proof,
      publicSignals: this._normalizePublicSignals(proof.publicSignals),
    };
  }

  public async calculateWitness(
    inputs: PrivateBurnCircuitGroth16,
  ): Promise<bigint[]> {
    return super.calculateWitness(inputs as any);
  }

  public async verifyProof(proof: ProofBurnCircuitGroth16): Promise<boolean> {
    return super.verifyProof({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public async generateCalldata(
    proof: ProofBurnCircuitGroth16,
  ): Promise<CalldataBurnCircuitGroth16> {
    return super.generateCalldata({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public getSignalNames(): string[] {
    return [
      "SenderPublicKey",
      "SenderBalanceC1",
      "SenderBalanceC2",
      "SenderVTBC1",
      "SenderVTBC2",
      "AuditorPublicKey",
      "AuditorPCT",
      "AuditorPCTAuthKey",
      "AuditorPCTNonce",
    ];
  }

  public getSignalDimensions(name: string): number[] {
    switch (name) {
      case "SenderPublicKey":
        return [2];
      case "SenderBalanceC1":
        return [2];
      case "SenderBalanceC2":
        return [2];
      case "SenderVTBC1":
        return [2];
      case "SenderVTBC2":
        return [2];
      case "AuditorPublicKey":
        return [2];
      case "AuditorPCT":
        return [4];
      case "AuditorPCTAuthKey":
        return [2];
      case "AuditorPCTNonce":
        return [];
      default:
        throw new Error(`Unknown signal name: ${name}`);
    }
  }

  private _normalizePublicSignals(
    publicSignals: PublicSignals,
  ): PublicBurnCircuitGroth16 {
    return normalizePublicSignals(
      publicSignals,
      this.getSignalNames(),
      this.getSignalDimensions,
    );
  }

  private _denormalizePublicSignals(
    publicSignals: PublicBurnCircuitGroth16,
  ): PublicSignals {
    return denormalizePublicSignals(publicSignals, this.getSignalNames());
  }
}

export default BurnCircuit;
