/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

import {
  CircuitZKit,
  CircuitZKitConfig,
  Groth16Proof,
  PlonkProof,
  Groth16ProofPoints,
  PlonkProofPoints,
  NumberLike,
  NumericString,
  PublicSignals,
  Groth16Implementer,
  PlonkImplementer,
} from "@solarity/zkit";

import { normalizePublicSignals, denormalizePublicSignals } from "../helpers";

export type PrivateMintCircuitGroth16 = {
  ValueToMint: NumberLike;
  ChainID: NumberLike;
  NullifierHash: NumberLike;
  ReceiverPublicKey: NumberLike[];
  ReceiverVTTC1: NumberLike[];
  ReceiverVTTC2: NumberLike[];
  ReceiverVTTRandom: NumberLike;
  ReceiverPCT: NumberLike[];
  ReceiverPCTAuthKey: NumberLike[];
  ReceiverPCTNonce: NumberLike;
  ReceiverPCTRandom: NumberLike;
  AuditorPublicKey: NumberLike[];
  AuditorPCT: NumberLike[];
  AuditorPCTAuthKey: NumberLike[];
  AuditorPCTNonce: NumberLike;
  AuditorPCTRandom: NumberLike;
};

export type PublicMintCircuitGroth16 = {
  ChainID: NumberLike;
  NullifierHash: NumberLike;
  ReceiverPublicKey: NumberLike[];
  ReceiverVTTC1: NumberLike[];
  ReceiverVTTC2: NumberLike[];
  ReceiverPCT: NumberLike[];
  ReceiverPCTAuthKey: NumberLike[];
  ReceiverPCTNonce: NumberLike;
  AuditorPublicKey: NumberLike[];
  AuditorPCT: NumberLike[];
  AuditorPCTAuthKey: NumberLike[];
  AuditorPCTNonce: NumberLike;
};

export type ProofMintCircuitGroth16 = {
  proof: Groth16Proof;
  publicSignals: PublicMintCircuitGroth16;
};

export type CalldataMintCircuitGroth16 = {
  proofPoints: Groth16ProofPoints;
  publicSignals: [
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
  ];
};

export class MintCircuit extends CircuitZKit<"groth16"> {
  constructor(config: CircuitZKitConfig) {
    super(config, new Groth16Implementer());
  }

  public async generateProof(
    inputs: PrivateMintCircuitGroth16,
  ): Promise<ProofMintCircuitGroth16> {
    const proof = await super.generateProof(inputs as any);

    return {
      proof: proof.proof,
      publicSignals: this._normalizePublicSignals(proof.publicSignals),
    };
  }

  public async calculateWitness(
    inputs: PrivateMintCircuitGroth16,
  ): Promise<bigint[]> {
    return super.calculateWitness(inputs as any);
  }

  public async verifyProof(proof: ProofMintCircuitGroth16): Promise<boolean> {
    return super.verifyProof({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public async generateCalldata(
    proof: ProofMintCircuitGroth16,
  ): Promise<CalldataMintCircuitGroth16> {
    return super.generateCalldata({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public getSignalNames(): string[] {
    return [
      "ChainID",
      "NullifierHash",
      "ReceiverPublicKey",
      "ReceiverVTTC1",
      "ReceiverVTTC2",
      "ReceiverPCT",
      "ReceiverPCTAuthKey",
      "ReceiverPCTNonce",
      "AuditorPublicKey",
      "AuditorPCT",
      "AuditorPCTAuthKey",
      "AuditorPCTNonce",
    ];
  }

  public getSignalDimensions(name: string): number[] {
    switch (name) {
      case "ChainID":
        return [];
      case "NullifierHash":
        return [];
      case "ReceiverPublicKey":
        return [2];
      case "ReceiverVTTC1":
        return [2];
      case "ReceiverVTTC2":
        return [2];
      case "ReceiverPCT":
        return [4];
      case "ReceiverPCTAuthKey":
        return [2];
      case "ReceiverPCTNonce":
        return [];
      case "AuditorPublicKey":
        return [2];
      case "AuditorPCT":
        return [4];
      case "AuditorPCTAuthKey":
        return [2];
      case "AuditorPCTNonce":
        return [];
      default:
        throw new Error(`Unknown signal name: ${name}`);
    }
  }

  private _normalizePublicSignals(
    publicSignals: PublicSignals,
  ): PublicMintCircuitGroth16 {
    return normalizePublicSignals(
      publicSignals,
      this.getSignalNames(),
      this.getSignalDimensions,
    );
  }

  private _denormalizePublicSignals(
    publicSignals: PublicMintCircuitGroth16,
  ): PublicSignals {
    return denormalizePublicSignals(publicSignals, this.getSignalNames());
  }
}

export default MintCircuit;
