/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

import {
  CircuitZKit,
  CircuitZKitConfig,
  Groth16Proof,
  PlonkProof,
  Groth16ProofPoints,
  PlonkProofPoints,
  NumberLike,
  NumericString,
  PublicSignals,
  Groth16Implementer,
  PlonkImplementer,
} from "@solarity/zkit";

import { normalizePublicSignals, denormalizePublicSignals } from "../helpers";

export type PrivateTransferCircuitGroth16 = {
  ValueToTransfer: NumberLike;
  SenderPrivateKey: NumberLike;
  SenderPublicKey: NumberLike[];
  SenderBalance: NumberLike;
  SenderBalanceC1: NumberLike[];
  SenderBalanceC2: NumberLike[];
  SenderVTTC1: NumberLike[];
  SenderVTTC2: NumberLike[];
  ReceiverPublicKey: NumberLike[];
  ReceiverVTTC1: NumberLike[];
  ReceiverVTTC2: NumberLike[];
  ReceiverVTTRandom: NumberLike;
  ReceiverPCT: NumberLike[];
  ReceiverPCTAuthKey: NumberLike[];
  ReceiverPCTNonce: NumberLike;
  ReceiverPCTRandom: NumberLike;
  AuditorPublicKey: NumberLike[];
  AuditorPCT: NumberLike[];
  AuditorPCTAuthKey: NumberLike[];
  AuditorPCTNonce: NumberLike;
  AuditorPCTRandom: NumberLike;
};

export type PublicTransferCircuitGroth16 = {
  SenderPublicKey: NumberLike[];
  SenderBalanceC1: NumberLike[];
  SenderBalanceC2: NumberLike[];
  SenderVTTC1: NumberLike[];
  SenderVTTC2: NumberLike[];
  ReceiverPublicKey: NumberLike[];
  ReceiverVTTC1: NumberLike[];
  ReceiverVTTC2: NumberLike[];
  ReceiverPCT: NumberLike[];
  ReceiverPCTAuthKey: NumberLike[];
  ReceiverPCTNonce: NumberLike;
  AuditorPublicKey: NumberLike[];
  AuditorPCT: NumberLike[];
  AuditorPCTAuthKey: NumberLike[];
  AuditorPCTNonce: NumberLike;
};

export type ProofTransferCircuitGroth16 = {
  proof: Groth16Proof;
  publicSignals: PublicTransferCircuitGroth16;
};

export type CalldataTransferCircuitGroth16 = {
  proofPoints: Groth16ProofPoints;
  publicSignals: [
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
  ];
};

export class TransferCircuit extends CircuitZKit<"groth16"> {
  constructor(config: CircuitZKitConfig) {
    super(config, new Groth16Implementer());
  }

  public async generateProof(
    inputs: PrivateTransferCircuitGroth16,
  ): Promise<ProofTransferCircuitGroth16> {
    const proof = await super.generateProof(inputs as any);

    return {
      proof: proof.proof,
      publicSignals: this._normalizePublicSignals(proof.publicSignals),
    };
  }

  public async calculateWitness(
    inputs: PrivateTransferCircuitGroth16,
  ): Promise<bigint[]> {
    return super.calculateWitness(inputs as any);
  }

  public async verifyProof(
    proof: ProofTransferCircuitGroth16,
  ): Promise<boolean> {
    return super.verifyProof({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public async generateCalldata(
    proof: ProofTransferCircuitGroth16,
  ): Promise<CalldataTransferCircuitGroth16> {
    return super.generateCalldata({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public getSignalNames(): string[] {
    return [
      "SenderPublicKey",
      "SenderBalanceC1",
      "SenderBalanceC2",
      "SenderVTTC1",
      "SenderVTTC2",
      "ReceiverPublicKey",
      "ReceiverVTTC1",
      "ReceiverVTTC2",
      "ReceiverPCT",
      "ReceiverPCTAuthKey",
      "ReceiverPCTNonce",
      "AuditorPublicKey",
      "AuditorPCT",
      "AuditorPCTAuthKey",
      "AuditorPCTNonce",
    ];
  }

  public getSignalDimensions(name: string): number[] {
    switch (name) {
      case "SenderPublicKey":
        return [2];
      case "SenderBalanceC1":
        return [2];
      case "SenderBalanceC2":
        return [2];
      case "SenderVTTC1":
        return [2];
      case "SenderVTTC2":
        return [2];
      case "ReceiverPublicKey":
        return [2];
      case "ReceiverVTTC1":
        return [2];
      case "ReceiverVTTC2":
        return [2];
      case "ReceiverPCT":
        return [4];
      case "ReceiverPCTAuthKey":
        return [2];
      case "ReceiverPCTNonce":
        return [];
      case "AuditorPublicKey":
        return [2];
      case "AuditorPCT":
        return [4];
      case "AuditorPCTAuthKey":
        return [2];
      case "AuditorPCTNonce":
        return [];
      default:
        throw new Error(`Unknown signal name: ${name}`);
    }
  }

  private _normalizePublicSignals(
    publicSignals: PublicSignals,
  ): PublicTransferCircuitGroth16 {
    return normalizePublicSignals(
      publicSignals,
      this.getSignalNames(),
      this.getSignalDimensions,
    );
  }

  private _denormalizePublicSignals(
    publicSignals: PublicTransferCircuitGroth16,
  ): PublicSignals {
    return denormalizePublicSignals(publicSignals, this.getSignalNames());
  }
}

export default TransferCircuit;
