/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

import {
  CircuitZKit,
  CircuitZKitConfig,
  Groth16Proof,
  PlonkProof,
  Groth16ProofPoints,
  PlonkProofPoints,
  NumberLike,
  NumericString,
  PublicSignals,
  Groth16Implementer,
  PlonkImplementer,
} from "@solarity/zkit";

import { normalizePublicSignals, denormalizePublicSignals } from "../helpers";

export type PrivateWithdrawCircuitGroth16 = {
  ValueToWithdraw: NumberLike;
  SenderPrivateKey: NumberLike;
  SenderPublicKey: NumberLike[];
  SenderBalance: NumberLike;
  SenderBalanceC1: NumberLike[];
  SenderBalanceC2: NumberLike[];
  AuditorPublicKey: NumberLike[];
  AuditorPCT: NumberLike[];
  AuditorPCTAuthKey: NumberLike[];
  AuditorPCTNonce: NumberLike;
  AuditorPCTRandom: NumberLike;
};

export type PublicWithdrawCircuitGroth16 = {
  ValueToWithdraw: NumberLike;
  SenderPublicKey: NumberLike[];
  SenderBalanceC1: NumberLike[];
  SenderBalanceC2: NumberLike[];
  AuditorPublicKey: NumberLike[];
  AuditorPCT: NumberLike[];
  AuditorPCTAuthKey: NumberLike[];
  AuditorPCTNonce: NumberLike;
};

export type ProofWithdrawCircuitGroth16 = {
  proof: Groth16Proof;
  publicSignals: PublicWithdrawCircuitGroth16;
};

export type CalldataWithdrawCircuitGroth16 = {
  proofPoints: Groth16ProofPoints;
  publicSignals: [
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
    NumericString,
  ];
};

export class WithdrawCircuit extends CircuitZKit<"groth16"> {
  constructor(config: CircuitZKitConfig) {
    super(config, new Groth16Implementer());
  }

  public async generateProof(
    inputs: PrivateWithdrawCircuitGroth16,
  ): Promise<ProofWithdrawCircuitGroth16> {
    const proof = await super.generateProof(inputs as any);

    return {
      proof: proof.proof,
      publicSignals: this._normalizePublicSignals(proof.publicSignals),
    };
  }

  public async calculateWitness(
    inputs: PrivateWithdrawCircuitGroth16,
  ): Promise<bigint[]> {
    return super.calculateWitness(inputs as any);
  }

  public async verifyProof(
    proof: ProofWithdrawCircuitGroth16,
  ): Promise<boolean> {
    return super.verifyProof({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public async generateCalldata(
    proof: ProofWithdrawCircuitGroth16,
  ): Promise<CalldataWithdrawCircuitGroth16> {
    return super.generateCalldata({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public getSignalNames(): string[] {
    return [
      "ValueToWithdraw",
      "SenderPublicKey",
      "SenderBalanceC1",
      "SenderBalanceC2",
      "AuditorPublicKey",
      "AuditorPCT",
      "AuditorPCTAuthKey",
      "AuditorPCTNonce",
    ];
  }

  public getSignalDimensions(name: string): number[] {
    switch (name) {
      case "ValueToWithdraw":
        return [];
      case "SenderPublicKey":
        return [2];
      case "SenderBalanceC1":
        return [2];
      case "SenderBalanceC2":
        return [2];
      case "AuditorPublicKey":
        return [2];
      case "AuditorPCT":
        return [4];
      case "AuditorPCTAuthKey":
        return [2];
      case "AuditorPCTNonce":
        return [];
      default:
        throw new Error(`Unknown signal name: ${name}`);
    }
  }

  private _normalizePublicSignals(
    publicSignals: PublicSignals,
  ): PublicWithdrawCircuitGroth16 {
    return normalizePublicSignals(
      publicSignals,
      this.getSignalNames(),
      this.getSignalDimensions,
    );
  }

  private _denormalizePublicSignals(
    publicSignals: PublicWithdrawCircuitGroth16,
  ): PublicSignals {
    return denormalizePublicSignals(publicSignals, this.getSignalNames());
  }
}

export default WithdrawCircuit;
